/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
    PrimePanel: typeof import('primevue/panel')['default']
    PrimePopover: typeof import('primevue/popover')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
